background = 0xFF2D2A2E
base = 0xFF403E41
text = 0xFFFCFCFA
alternate_base = 0xFF353237
bright_text = 0xFF78DCE8
accent = 0xFF78DCE8
link_text = 0xFF78DCE8
accent_secondary = 0xFFAB9DF2
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
