# theme: monokai-dark
code_syntax_highlight = "monokai"
full_screen_fg = "#FCFCFA"
full_screen_bg = "#2D2A2E"
gradient_color = ["#78DCE8", "#AB9DF2"]
file_panel_fg = "#FCFCFA"
file_panel_bg = "#2D2A2E"
file_panel_border = "#5B595C"
file_panel_border_active = "#78DCE8"
file_panel_top_directory_icon = "#78DCE8"
file_panel_top_path = "#FCFCFA"
file_panel_item_selected_fg = "#FCFCFA"
file_panel_item_selected_bg = "#403E41"
footer_fg = "#FCFCFA"
footer_bg = "#221F22"
footer_border = "#5B595C"
footer_border_active = "#78DCE8"
sidebar_fg = "#FCFCFA"
sidebar_bg = "#221F22"
sidebar_title = "#78DCE8"
sidebar_border = "#5B595C"
sidebar_border_active = "#78DCE8"
sidebar_item_selected_fg = "#FCFCFA"
sidebar_item_selected_bg = "#403E41"
sidebar_divider = "#5B595C"
modal_fg = "#FCFCFA"
modal_bg = "#2D2A2E"
modal_border_active = "#78DCE8"
modal_cancel_fg = "#19181A"
modal_cancel_bg = "#939293"
modal_confirm_fg = "#19181A"
modal_confirm_bg = "#78DCE8"
help_menu_hotkey = "#78DCE8"
help_menu_title = "#FCFCFA"
cursor = "#FCFCFA"
correct = "#A9DC76"
error = "#FF6188"
hint = "#78DCE8"
cancel = "#939293"
